version: '3'
services:
   mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
     MYSQL_ROOT_PASSWORD: root
    ports:
     - 3306:3306
   spring_app:
    image: mednsi/devopsspringboot
    container_name: devopsspringboot
    restart: on-failure
    ports:
     - 8089:8089
    depends_on:
     - mysqldb
