version: '3.7'
services:
  ci-db:
    container_name: ci-db
    image: mysql:8.0
    networks:
      - ci-network
    environment:
      - MYSQL_USER=emna
      - MYSQL_PASSWORD=EmnaR1+3
      - MYSQL_DATABASE=achatdb
      - MYSQL_ROOT_PASSWORD=EmnaR1+2
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always

  ci-app:
    container_name: ci-spring
    image: docker.io/emnar12/projectdevops:latest
    ports:
      - "8089:8089"
    networks:
      - ci-network
    depends_on:
      - ci-db
    environment:
      - MYSQL_HOST=ci-db
      - MYSQL_USERNAME=emna
      - MYSQL_PASSWORD=EmnaR1+3
      - MYSQL_DATABASE=achatdb
      - MYSQL_PORT=3306


networks:
  ci-network:
    name: ci-network

volumes:
  dbvol:
