version: '3.7'
services:
  ci-app-front:
    container_name: ci-angular
    image: docker.io/fares156324/crudtutofronfares:latest
    ports:
      - "8888:80"
    networks:
      - ci-network
  ci-db:
    container_name: ci-db
    image: mysql:8.0
    networks:
      - ci-network
    environment:
      - MYSQL_USER=fares
      - MYSQL_PASSWORD=Fares1+2
      - MYSQL_DATABASE=achatdb
      - MYSQL_ROOT_PASSWORD=Akrem1+2
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always

  ci-app:
    container_name: ci-spring
    image: docker.io/fares156324/fares123:latest
    ports:
      - "8089:8089"
    networks:
      - ci-network
    depends_on:
      - ci-db
    environment:
      - MYSQL_HOST=ci-db
      - MYSQL_USERNAME=fares
      - MYSQL_PASSWORD=Fares1+2
      - MYSQL_DATABASE=achatdb
      - MYSQL_PORT=3306


networks:
  ci-network:
    name: ci-network

volumes:
  dbvol:
